# Generated by Django 4.2.3 on 2023-09-02 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horas_de_vida_util', models.PositiveIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_de_energia_kw_h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horas_de_uso_acumulado', models.PositiveIntegerField(default=0)),
                ('horas_de_uso_mantenimiento', models.PositiveIntegerField()),
                ('proximo_mantenimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_de_uso', models.PositiveIntegerField()),
                ('fecha_alquiler', models.DateTimeField(auto_now_add=True)),
                ('lavadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavadoras.lavadora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
